// Datos oficiales de la Asociación Panameña de Beyblade - Ranking Nacional Individual Categoria Open Temporada 1
export interface HistoricalRankingRow {
  rank: number;
  blader: string;
  tournaments_played: number;
  matches_played: number;
  matches_won: number;
  matches_lost: number;
  points_for: number;
  points_against: number;
  bonus_points: number;
  warnings: number;
  win_rate: string;
  total_points: number;
}

export const APB_SEASON_1_RANKINGS: HistoricalRankingRow[] = [
  { rank: 1, blader: "Yorch", tournaments_played: 15, matches_played: 145, matches_won: 96, matches_lost: 49, points_for: 519, points_against: 317, bonus_points: 444, warnings: 0, win_rate: "66%", total_points: 646 },
  { rank: 2, blader: "Woonka", tournaments_played: 14, matches_played: 150, matches_won: 94, matches_lost: 56, points_for: 484, points_against: 353, bonus_points: 352, warnings: 0, win_rate: "63%", total_points: 483 },
  { rank: 3, blader: "Kanghy", tournaments_played: 16, matches_played: 157, matches_won: 87, matches_lost: 70, points_for: 505, points_against: 417, bonus_points: 392, warnings: 0, win_rate: "55%", total_points: 480 },
  { rank: 4, blader: "Raines", tournaments_played: 12, matches_played: 117, matches_won: 73, matches_lost: 44, points_for: 429, points_against: 311, bonus_points: 347, warnings: 0, win_rate: "62%", total_points: 465 },
  { rank: 5, blader: "Zirox", tournaments_played: 16, matches_played: 138, matches_won: 78, matches_lost: 60, points_for: 440, points_against: 354, bonus_points: 352, warnings: 0, win_rate: "57%", total_points: 438 },
  { rank: 6, blader: "Káiser", tournaments_played: 12, matches_played: 116, matches_won: 70, matches_lost: 46, points_for: 416, points_against: 323, bonus_points: 286, warnings: 0, win_rate: "60%", total_points: 379 },
  { rank: 7, blader: "Baco", tournaments_played: 16, matches_played: 149, matches_won: 81, matches_lost: 68, points_for: 479, points_against: 413, bonus_points: 304, warnings: 0, win_rate: "54%", total_points: 370 },
  { rank: 8, blader: "RADD", tournaments_played: 12, matches_played: 107, matches_won: 69, matches_lost: 38, points_for: 370, points_against: 268, bonus_points: 241, warnings: 0, win_rate: "64%", total_points: 343 },
  { rank: 9, blader: "Raphaeru", tournaments_played: 10, matches_played: 91, matches_won: 56, matches_lost: 35, points_for: 305, points_against: 222, bonus_points: 237, warnings: 0, win_rate: "62%", total_points: 320 },
  { rank: 10, blader: "Wolf", tournaments_played: 10, matches_played: 99, matches_won: 55, matches_lost: 44, points_for: 330, points_against: 266, bonus_points: 240, warnings: 0, win_rate: "56%", total_points: 304 },
  { rank: 11, blader: "ProdyQ", tournaments_played: 13, matches_played: 125, matches_won: 67, matches_lost: 58, points_for: 369, points_against: 353, bonus_points: 283, warnings: 0, win_rate: "54%", total_points: 299 },
  { rank: 12, blader: "Panda", tournaments_played: 8, matches_played: 65, matches_won: 36, matches_lost: 29, points_for: 269, points_against: 223, bonus_points: 237, warnings: 0, win_rate: "55%", total_points: 283 },
  { rank: 13, blader: "Jiji", tournaments_played: 7, matches_played: 62, matches_won: 36, matches_lost: 26, points_for: 193, points_against: 172, bonus_points: 206, warnings: 0, win_rate: "58%", total_points: 227 },
  { rank: 14, blader: "Scorpio", tournaments_played: 5, matches_played: 71, matches_won: 40, matches_lost: 31, points_for: 210, points_against: 169, bonus_points: 153, warnings: 0, win_rate: "56%", total_points: 194 },
  { rank: 15, blader: "C J", tournaments_played: 11, matches_played: 97, matches_won: 60, matches_lost: 37, points_for: 269, points_against: 270, bonus_points: 178, warnings: 0, win_rate: "62%", total_points: 177 },
  { rank: 16, blader: "Dimetrodon", tournaments_played: 7, matches_played: 50, matches_won: 27, matches_lost: 23, points_for: 139, points_against: 144, bonus_points: 181, warnings: 0, win_rate: "54%", total_points: 176 },
  { rank: 17, blader: "King", tournaments_played: 10, matches_played: 75, matches_won: 41, matches_lost: 34, points_for: 231, points_against: 221, bonus_points: 159, warnings: 0, win_rate: "55%", total_points: 169 },
  { rank: 18, blader: "Gurren Iann", tournaments_played: 6, matches_played: 44, matches_won: 23, matches_lost: 21, points_for: 133, points_against: 125, bonus_points: 153, warnings: 0, win_rate: "52%", total_points: 161 },
  { rank: 19, blader: "Pejex", tournaments_played: 10, matches_played: 67, matches_won: 29, matches_lost: 38, points_for: 195, points_against: 204, bonus_points: 166, warnings: 0, win_rate: "43%", total_points: 157 },
  { rank: 20, blader: "Bubbles", tournaments_played: 10, matches_played: 81, matches_won: 33, matches_lost: 48, points_for: 198, points_against: 236, bonus_points: 181, warnings: 0, win_rate: "41%", total_points: 143 },
  { rank: 21, blader: "Krizia Olmos", tournaments_played: 10, matches_played: 77, matches_won: 42, matches_lost: 35, points_for: 224, points_against: 230, bonus_points: 141, warnings: 0, win_rate: "55%", total_points: 135 },
  { rank: 22, blader: "Sombra", tournaments_played: 10, matches_played: 75, matches_won: 33, matches_lost: 42, points_for: 196, points_against: 226, bonus_points: 131, warnings: 0, win_rate: "44%", total_points: 101 },
  { rank: 23, blader: "Kurenai", tournaments_played: 9, matches_played: 71, matches_won: 27, matches_lost: 44, points_for: 193, points_against: 230, bonus_points: 138, warnings: 0, win_rate: "38%", total_points: 101 },
  { rank: 24, blader: "Parzival", tournaments_played: 4, matches_played: 40, matches_won: 21, matches_lost: 19, points_for: 95, points_against: 103, bonus_points: 98, warnings: 0, win_rate: "53%", total_points: 90 },
  { rank: 25, blader: "Asuma", tournaments_played: 2, matches_played: 7, matches_won: 4, matches_lost: 3, points_for: 79, points_against: 50, bonus_points: 59, warnings: 0, win_rate: "57%", total_points: 88 },
  { rank: 26, blader: "Mia Blader", tournaments_played: 3, matches_played: 35, matches_won: 20, matches_lost: 15, points_for: 107, points_against: 86, bonus_points: 51, warnings: 0, win_rate: "57%", total_points: 72 },
  { rank: 27, blader: "Sollux", tournaments_played: 15, matches_played: 100, matches_won: 37, matches_lost: 63, points_for: 248, points_against: 332, bonus_points: 154, warnings: 0, win_rate: "37%", total_points: 70 },
  { rank: 28, blader: "Rex1243", tournaments_played: 5, matches_played: 35, matches_won: 17, matches_lost: 18, points_for: 99, points_against: 111, bonus_points: 74, warnings: 0, win_rate: "49%", total_points: 62 },
  { rank: 29, blader: "Julio Jaen", tournaments_played: 1, matches_played: 13, matches_won: 6, matches_lost: 7, points_for: 37, points_against: 37, bonus_points: 60, warnings: 0, win_rate: "46%", total_points: 60 },
  { rank: 30, blader: "Metaman", tournaments_played: 3, matches_played: 21, matches_won: 9, matches_lost: 12, points_for: 55, points_against: 60, bonus_points: 58, warnings: 0, win_rate: "43%", total_points: 53 },
  { rank: 31, blader: "Bellota", tournaments_played: 6, matches_played: 32, matches_won: 13, matches_lost: 19, points_for: 87, points_against: 107, bonus_points: 72, warnings: 0, win_rate: "41%", total_points: 52 },
  { rank: 32, blader: "Geovane NG", tournaments_played: 3, matches_played: 22, matches_won: 10, matches_lost: 12, points_for: 63, points_against: 64, bonus_points: 53, warnings: 0, win_rate: "45%", total_points: 52 },
  { rank: 33, blader: "Diego Q.", tournaments_played: 3, matches_played: 21, matches_won: 10, matches_lost: 11, points_for: 61, points_against: 61, bonus_points: 52, warnings: 0, win_rate: "48%", total_points: 52 },
  { rank: 34, blader: "Gengar", tournaments_played: 6, matches_played: 31, matches_won: 15, matches_lost: 16, points_for: 86, points_against: 100, bonus_points: 59, warnings: 0, win_rate: "48%", total_points: 45 },
  { rank: 35, blader: "Saviñon Sr", tournaments_played: 2, matches_played: 15, matches_won: 7, matches_lost: 8, points_for: 42, points_against: 43, bonus_points: 45, warnings: 0, win_rate: "47%", total_points: 44 },
  { rank: 36, blader: "Nova", tournaments_played: 3, matches_played: 22, matches_won: 8, matches_lost: 14, points_for: 60, points_against: 66, bonus_points: 46, warnings: 0, win_rate: "36%", total_points: 40 },
  { rank: 37, blader: "Miguel de sedas", tournaments_played: 2, matches_played: 18, matches_won: 11, matches_lost: 7, points_for: 55, points_against: 44, bonus_points: 28, warnings: 0, win_rate: "61%", total_points: 39 },
  { rank: 38, blader: "Saviñon Jr", tournaments_played: 2, matches_played: 13, matches_won: 5, matches_lost: 8, points_for: 41, points_against: 32, bonus_points: 28, warnings: 0, win_rate: "38%", total_points: 37 },
  { rank: 39, blader: "Zero", tournaments_played: 2, matches_played: 13, matches_won: 7, matches_lost: 6, points_for: 43, points_against: 41, bonus_points: 30, warnings: 0, win_rate: "54%", total_points: 32 },
  { rank: 40, blader: "Kai", tournaments_played: 5, matches_played: 29, matches_won: 11, matches_lost: 18, points_for: 76, points_against: 100, bonus_points: 55, warnings: 0, win_rate: "38%", total_points: 31 },
  { rank: 41, blader: "Alejandro LUNA", tournaments_played: 1, matches_played: 7, matches_won: 4, matches_lost: 3, points_for: 23, points_against: 17, bonus_points: 25, warnings: 0, win_rate: "57%", total_points: 31 },
  { rank: 42, blader: "Damir", tournaments_played: 2, matches_played: 18, matches_won: 10, matches_lost: 8, points_for: 50, points_against: 57, bonus_points: 36, warnings: 0, win_rate: "56%", total_points: 29 },
  { rank: 43, blader: "Twilight", tournaments_played: 5, matches_played: 36, matches_won: 15, matches_lost: 21, points_for: 92, points_against: 120, bonus_points: 56, warnings: 0, win_rate: "42%", total_points: 28 },
  { rank: 44, blader: "Johanes V.", tournaments_played: 2, matches_played: 10, matches_won: 6, matches_lost: 4, points_for: 32, points_against: 27, bonus_points: 23, warnings: 0, win_rate: "60%", total_points: 28 },
  { rank: 45, blader: "Lance", tournaments_played: 2, matches_played: 12, matches_won: 7, matches_lost: 5, points_for: 40, points_against: 36, bonus_points: 23, warnings: 0, win_rate: "58%", total_points: 27 },
  { rank: 46, blader: "Aletaco", tournaments_played: 1, matches_played: 6, matches_won: 4, matches_lost: 2, points_for: 17, points_against: 16, bonus_points: 25, warnings: 0, win_rate: "67%", total_points: 26 },
  { rank: 47, blader: "Hannie", tournaments_played: 1, matches_played: 8, matches_won: 5, matches_lost: 3, points_for: 21, points_against: 20, bonus_points: 21, warnings: 0, win_rate: "63%", total_points: 22 },
  { rank: 48, blader: "Juan Davild", tournaments_played: 2, matches_played: 9, matches_won: 3, matches_lost: 6, points_for: 23, points_against: 20, bonus_points: 18, warnings: 0, win_rate: "33%", total_points: 21 },
  { rank: 49, blader: "Samux", tournaments_played: 1, matches_played: 11, matches_won: 6, matches_lost: 5, points_for: 29, points_against: 33, bonus_points: 21, warnings: 0, win_rate: "55%", total_points: 17 },
  { rank: 50, blader: "juan diego", tournaments_played: 1, matches_played: 11, matches_won: 5, matches_lost: 6, points_for: 29, points_against: 34, bonus_points: 21, warnings: 0, win_rate: "45%", total_points: 16 },
  { rank: 51, blader: "Superior Slayer", tournaments_played: 1, matches_played: 5, matches_won: 2, matches_lost: 3, points_for: 21, points_against: 28, bonus_points: 21, warnings: 0, win_rate: "40%", total_points: 14 },
  { rank: 52, blader: "Arkham", tournaments_played: 2, matches_played: 17, matches_won: 5, matches_lost: 12, points_for: 41, points_against: 50, bonus_points: 23, warnings: 0, win_rate: "29%", total_points: 14 },
  { rank: 53, blader: "Chris", tournaments_played: 1, matches_played: 7, matches_won: 3, matches_lost: 4, points_for: 22, points_against: 22, bonus_points: 13, warnings: 0, win_rate: "43%", total_points: 13 },
  { rank: 54, blader: "Niko", tournaments_played: 1, matches_played: 5, matches_won: 3, matches_lost: 2, points_for: 16, points_against: 14, bonus_points: 10, warnings: 0, win_rate: "60%", total_points: 12 },
  { rank: 55, blader: "Papi Jake", tournaments_played: 3, matches_played: 20, matches_won: 6, matches_lost: 14, points_for: 50, points_against: 70, bonus_points: 31, warnings: 0, win_rate: "30%", total_points: 11 },
  { rank: 56, blader: "Alphangel", tournaments_played: 4, matches_played: 20, matches_won: 4, matches_lost: 16, points_for: 43, points_against: 69, bonus_points: 36, warnings: 0, win_rate: "20%", total_points: 10 },
  { rank: 57, blader: "JohnnyX", tournaments_played: 1, matches_played: 7, matches_won: 3, matches_lost: 4, points_for: 21, points_against: 22, bonus_points: 10, warnings: 0, win_rate: "43%", total_points: 9 },
  { rank: 58, blader: "Diogenes E.", tournaments_played: 1, matches_played: 4, matches_won: 2, matches_lost: 2, points_for: 11, points_against: 12, bonus_points: 10, warnings: 0, win_rate: "50%", total_points: 9 },
  { rank: 59, blader: "Ignacio", tournaments_played: 1, matches_played: 4, matches_won: 1, matches_lost: 3, points_for: 13, points_against: 9, bonus_points: 5, warnings: 0, win_rate: "25%", total_points: 9 },
  { rank: 60, blader: "SIr Lancelot", tournaments_played: 1, matches_played: 3, matches_won: 1, matches_lost: 2, points_for: 8, points_against: 9, bonus_points: 10, warnings: 0, win_rate: "33%", total_points: 9 },
  { rank: 61, blader: "Jorge Valdes", tournaments_played: 3, matches_played: 21, matches_won: 7, matches_lost: 14, points_for: 38, points_against: 69, bonus_points: 39, warnings: 0, win_rate: "33%", total_points: 8 },
  { rank: 62, blader: "Emmanuel", tournaments_played: 1, matches_played: 3, matches_won: 1, matches_lost: 2, points_for: 7, points_against: 9, bonus_points: 10, warnings: 0, win_rate: "33%", total_points: 8 },
  { rank: 63, blader: "Ana Carolina", tournaments_played: 2, matches_played: 11, matches_won: 4, matches_lost: 7, points_for: 21, points_against: 37, bonus_points: 23, warnings: 0, win_rate: "36%", total_points: 7 },
  { rank: 64, blader: "Maleantin", tournaments_played: 1, matches_played: 6, matches_won: 1, matches_lost: 5, points_for: 12, points_against: 12, bonus_points: 5, warnings: 0, win_rate: "17%", total_points: 5 },
  { rank: 65, blader: "Bastan", tournaments_played: 1, matches_played: 3, matches_won: 1, matches_lost: 2, points_for: 6, points_against: 12, bonus_points: 10, warnings: 0, win_rate: "33%", total_points: 4 },
  { rank: 67, blader: "Edson", tournaments_played: 1, matches_played: 6, matches_won: 2, matches_lost: 4, points_for: 15, points_against: 17, bonus_points: 5, warnings: 0, win_rate: "33%", total_points: 3 },
  { rank: 68, blader: "Ramses", tournaments_played: 1, matches_played: 8, matches_won: 3, matches_lost: 5, points_for: 21, points_against: 26, bonus_points: 7, warnings: 0, win_rate: "38%", total_points: 2 },
  { rank: 69, blader: "Zahik", tournaments_played: 2, matches_played: 7, matches_won: 1, matches_lost: 6, points_for: 10, points_against: 25, bonus_points: 15, warnings: 0, win_rate: "14%", total_points: 0 },
  { rank: 70, blader: "Isaias S.", tournaments_played: 1, matches_played: 4, matches_won: 1, matches_lost: 3, points_for: 5, points_against: 15, bonus_points: 10, warnings: 0, win_rate: "25%", total_points: 0 },
  { rank: 71, blader: "Ceferino Sr.", tournaments_played: 2, matches_played: 8, matches_won: 2, matches_lost: 6, points_for: 15, points_against: 26, bonus_points: 10, warnings: 0, win_rate: "25%", total_points: -1 },
  { rank: 72, blader: "Tomyyaser", tournaments_played: 1, matches_played: 6, matches_won: 2, matches_lost: 4, points_for: 13, points_against: 20, bonus_points: 5, warnings: 0, win_rate: "33%", total_points: -2 },
  { rank: 73, blader: "Salomon Nieto", tournaments_played: 1, matches_played: 5, matches_won: 1, matches_lost: 4, points_for: 5, points_against: 17, bonus_points: 10, warnings: 0, win_rate: "20%", total_points: -2 },
  { rank: 74, blader: "Noah Herbert", tournaments_played: 1, matches_played: 5, matches_won: 2, matches_lost: 3, points_for: 11, points_against: 19, bonus_points: 5, warnings: 0, win_rate: "40%", total_points: -3 },
  { rank: 75, blader: "Alejandro Jaen", tournaments_played: 1, matches_played: 5, matches_won: 1, matches_lost: 4, points_for: 11, points_against: 19, bonus_points: 5, warnings: 0, win_rate: "20%", total_points: -3 },
  { rank: 76, blader: "Joel Caballero", tournaments_played: 1, matches_played: 4, matches_won: 0, matches_lost: 4, points_for: 5, points_against: 18, bonus_points: 10, warnings: 0, win_rate: "0%", total_points: -3 },
  { rank: 77, blader: "Alejandro D.", tournaments_played: 1, matches_played: 4, matches_won: 0, matches_lost: 4, points_for: 3, points_against: 16, bonus_points: 10, warnings: 0, win_rate: "0%", total_points: -3 },
  { rank: 78, blader: "Ethan Mendoza", tournaments_played: 2, matches_played: 9, matches_won: 2, matches_lost: 7, points_for: 14, points_against: 34, bonus_points: 15, warnings: 0, win_rate: "22%", total_points: -5 },
  { rank: 79, blader: "Javier Abrego", tournaments_played: 1, matches_played: 5, matches_won: 1, matches_lost: 4, points_for: 9, points_against: 19, bonus_points: 5, warnings: 0, win_rate: "20%", total_points: -5 },
  { rank: 80, blader: "aeloz Cogley", tournaments_played: 1, matches_played: 5, matches_won: 1, matches_lost: 4, points_for: 8, points_against: 18, bonus_points: 5, warnings: 0, win_rate: "20%", total_points: -5 },
  { rank: 81, blader: "Wistom Mendez", tournaments_played: 1, matches_played: 5, matches_won: 1, matches_lost: 4, points_for: 8, points_against: 19, bonus_points: 5, warnings: 0, win_rate: "20%", total_points: -6 },
  { rank: 82, blader: "Alesito33", tournaments_played: 1, matches_played: 4, matches_won: 0, matches_lost: 4, points_for: 3, points_against: 19, bonus_points: 10, warnings: 0, win_rate: "0%", total_points: -6 },
  { rank: 83, blader: "Abraham Garcia", tournaments_played: 3, matches_played: 20, matches_won: 6, matches_lost: 14, points_for: 35, points_against: 71, bonus_points: 28, warnings: 0, win_rate: "30%", total_points: -8 },
  { rank: 84, blader: "Cerferino Jr.", tournaments_played: 2, matches_played: 10, matches_won: 3, matches_lost: 7, points_for: 11, points_against: 29, bonus_points: 10, warnings: 0, win_rate: "30%", total_points: -8 },
  { rank: 85, blader: "Cristofer Scott", tournaments_played: 1, matches_played: 5, matches_won: 0, matches_lost: 5, points_for: 2, points_against: 21, bonus_points: 10, warnings: 0, win_rate: "0%", total_points: -9 },
  { rank: 86, blader: "Lukas Axel", tournaments_played: 1, matches_played: 5, matches_won: 1, matches_lost: 4, points_for: 6, points_against: 20, bonus_points: 5, warnings: 0, win_rate: "20%", total_points: -9 },
  { rank: 87, blader: "Fernando", tournaments_played: 1, matches_played: 4, matches_won: 0, matches_lost: 4, points_for: 2, points_against: 17, bonus_points: 5, warnings: 0, win_rate: "0%", total_points: -10 },
  { rank: 88, blader: "Lore", tournaments_played: 1, matches_played: 4, matches_won: 0, matches_lost: 4, points_for: 0, points_against: 16, bonus_points: 5, warnings: 0, win_rate: "0%", total_points: -11 },
  { rank: 89, blader: "Alex", tournaments_played: 2, matches_played: 18, matches_won: 3, matches_lost: 15, points_for: 34, points_against: 69, bonus_points: 23, warnings: 0, win_rate: "17%", total_points: -12 },
  { rank: 90, blader: "Lazuli", tournaments_played: 1, matches_played: 5, matches_won: 0, matches_lost: 5, points_for: 5, points_against: 22, bonus_points: 5, warnings: 0, win_rate: "0%", total_points: -12 },
  { rank: 91, blader: "Sonico", tournaments_played: 1, matches_played: 6, matches_won: 0, matches_lost: 6, points_for: 6, points_against: 25, bonus_points: 5, warnings: 0, win_rate: "0%", total_points: -14 },
  { rank: 92, blader: "Rebecca", tournaments_played: 1, matches_played: 6, matches_won: 0, matches_lost: 6, points_for: 5, points_against: 26, bonus_points: 5, warnings: 0, win_rate: "0%", total_points: -16 },
  { rank: 93, blader: "Juanita", tournaments_played: 5, matches_played: 25, matches_won: 6, matches_lost: 19, points_for: 49, points_against: 96, bonus_points: 30, warnings: 0, win_rate: "24%", total_points: -17 },
  { rank: 94, blader: "Nessa", tournaments_played: 2, matches_played: 10, matches_won: 2, matches_lost: 8, points_for: 16, points_against: 52, bonus_points: 18, warnings: 0, win_rate: "20%", total_points: -18 },
  { rank: 95, blader: "David Navarro", tournaments_played: 1, matches_played: 5, matches_won: 0, matches_lost: 5, points_for: 1, points_against: 24, bonus_points: 5, warnings: 0, win_rate: "0%", total_points: -18 },
  { rank: 96, blader: "Danilo", tournaments_played: 1, matches_played: 6, matches_won: 0, matches_lost: 6, points_for: 0, points_against: 24, bonus_points: 5, warnings: 0, win_rate: "0%", total_points: -19 }
];
